# Generated by Django 5.0.4 on 2024-04-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='booked_by',
        ),
    ]
