# Generated by Django 5.0.4 on 2024-04-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_remove_flight_booked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='available_seats',
            field=models.IntegerField(),
        ),
    ]
