# Generated by Django 5.0.4 on 2024-04-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_alter_booking_seat_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='flight',
            new_name='flight_id',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='user_id',
        ),
    ]
