# Generated by Django 5.0.4 on 2024-04-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_rename_flight_booking_flight_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='flight_id',
            new_name='flight',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
    ]
